server:
  port: 8899
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lzp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: '!QAZ2wsx'

  redis:
    host: 192.168.1.20
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
# mybatis
# 下划线转驼峰开启
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  # mapper扫描位置
  mapper-locations: classpath:mapper/*.xml